language: cpp
os: 
  - osx
  - linux
compiler: gcc
sudo: true
before_install:
  - export CC=mpicc
  - export CXX=mpicxx
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    #  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo rm /usr/local/include/c++ ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mpich2 lapack; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cmake libmpich-dev liblapack-dev ; fi
before_script: 
  - export CXX=mpicxx
  - mkdir build
  - cd build
  - cmake .. 
script: make && make test



